export const UI_STRINGS = {
    COMMON: {
        APP_NAME: 'Pakky',
        LOADING: 'Loading...',
        CANCEL: 'Cancel',
        SAVE: 'Save',
        DELETE: 'Delete',
        EDIT: 'Edit',
        CLOSE: 'Close',
        UNKNOWN: 'Unknown',
        QUIT: 'Quit',
    },
    HOME: {
        TITLE: 'Library',
        DESCRIPTION: 'Search and manage your packages.',
        SEARCH_PLACEHOLDER: 'Search packages...',
        HOMEBREW_MISSING: 'Homebrew is not installed/detected',
        HOMEBREW_INSTALLING: 'Installing Homebrew... This may take a few minutes.',
        HOMEBREW_INSTALL_BUTTON: 'Install Homebrew',
        HOMEBREW_INSTALL_SUCCESS: 'Homebrew installed successfully!',
        HOMEBREW_INSTALL_ERROR: 'Failed to install Homebrew. Please check the logs.',
        TIP_CONFIG: 'Tip: You can also import a config file using the sidebar',
        FOOTER_INFO: 'Homebrew',
    },
    QUEUE: {
        TITLE: 'Queue',
        EMPTY_TITLE: 'Your queue is empty',
        EMPTY_DESCRIPTION: 'Search for packages using the search bar above, or start with a pre-made configuration.',
        BROWSE_PRESETS: 'Browse Presets',
        SEARCH_PACKAGES: 'Search Packages',
        PENDING: 'pending',
        INSTALLED: 'installed',
        EXPORT: 'Export',
        CLEAR: 'Clear',
        INSTALL_ALL: 'Install All',
        CHECKING: 'Checking...',
    },
    SETTINGS: {
        TITLE: 'Settings',
        DESCRIPTION: 'Manage your preferences',
        PROFILE_TITLE: 'Profile',
        PROFILE_DESCRIPTION: 'Your personal information',
        NAME_LABEL: 'Name',
        SAVING: 'Saving...',
        PLATFORM_LABEL: 'Platform',
        ARCH_LABEL: 'Architecture',
        HOSTNAME_LABEL: 'Hostname',
        FIRST_LAUNCH_LABEL: 'First Launch',
        ABOUT_TITLE: 'About',
        ABOUT_DESCRIPTION: 'Application information',
        VERSION_LABEL: 'Version',
        PACKAGE_MANAGER_LABEL: 'Package Manager',
        DANGER_ZONE_TITLE: 'Danger Zone',
        DANGER_ZONE_DESCRIPTION: 'Irreversible actions',
        RESET_TITLE: 'Reset Configuration',
        RESET_DESCRIPTION: 'Clear all settings and restart onboarding',
        RESET_BUTTON: 'Reset',
        RESETTING_BUTTON: 'Resetting...',
        QUIT_TITLE: 'Quit Application',
        QUIT_DESCRIPTION: 'Close Pakky completely',
        RESET_DIALOG_TITLE: 'Reset Configuration',
        RESET_DIALOG_DESCRIPTION: 'This action cannot be undone.',
        RESET_WARNING: 'Are you sure you want to reset your configuration? This will:',
        RESET_WARNING_ITEMS: [
            'Clear all your settings',
            'Remove your profile information',
            'Restart the onboarding process'
        ],
    },
    ERRORS: {
        GENERIC_INSTALL_FAILED: 'Installation failed',
        GENERIC_CANCEL_FAILED: 'Failed to cancel',
        EXPORT_FAILED: 'Failed to export config',
        SAVE_NAME_FAILED: 'Failed to save name',
        RESET_CONFIG_FAILED: 'Failed to reset config',
        QUIT_FAILED: 'Failed to quit',
    }
} as const;
